name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
